name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        version: 1.12
    - name: Test with Gradle
      run: ./gradlew test
