name: publish

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 1.12
        uses: actions/setup-java@v1
        with:
          java-version: 1.12

      - name: Test with Gradle
        run: ./gradlew test

  maven_publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 1.12
        uses: actions/setup-java@v1
        with:
          java-version: 1.12

      - name: Authenticate for GitHub Packages
        run: |
          ./gradlew addCredentials --key auritylab.github.username --value AurityLab
          ./gradlew addCredentials --key auritylab.github.password --value ${{ secrets.GITHUB_TOKEN }}

      - name: Publish with Gradle
        run: ./gradlew publish
